"""first

Revision ID: a8a75df2366a
Revises: 
Create Date: 2021-10-28 13:49:28.381696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8a75df2366a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist',
    sa.Column('playlistId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('playlistId')
    )
    op.create_table('song',
    sa.Column('songId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('productionYear', sa.Integer(), nullable=True),
    sa.Column('length', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('songId')
    )
    op.create_table('user',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('userName', sa.String(length=20), nullable=False),
    sa.Column('firstName', sa.String(length=20), nullable=False),
    sa.Column('lastName', sa.String(length=25), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=True),
    sa.Column('userStatus', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('playlistssongs',
    sa.Column('songId', sa.Integer(), nullable=False),
    sa.Column('playlistId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['playlistId'], ['playlist.playlistId'], ),
    sa.ForeignKeyConstraint(['songId'], ['song.songId'], ),
    sa.PrimaryKeyConstraint('songId', 'playlistId')
    )
    op.create_table('privateplaylist',
    sa.Column('privateplaylistId', sa.Integer(), nullable=False),
    sa.Column('playlistId', sa.Integer(), nullable=True),
    sa.Column('Id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Id'], ['user.Id'], ),
    sa.ForeignKeyConstraint(['playlistId'], ['playlist.playlistId'], ),
    sa.PrimaryKeyConstraint('privateplaylistId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('privateplaylist')
    op.drop_table('playlistssongs')
    op.drop_table('user')
    op.drop_table('song')
    op.drop_table('playlist')
    # ### end Alembic commands ###
